name: nice
description: 'A new Flutter project.'

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  odu_core:
    git:
      url: https://github.com/pretodev/odu_core.git
      ref: main

  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  cloud_firestore: ^6.1.1
  material_symbols_icons: ^4.2892.0
  firebase_core: ^4.3.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  dio: ^5.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
